from __future__ import annotations

from importlib import import_module


_EXPORTS = {
    "SyntheticSchema": ".schema",
    "FieldSchema": ".schema",
    "ScreenSchema": ".schema",
    "SyntheticEngine": ".engine",
    "DataProvider": ".providers",
    "ProviderRegistry": ".providers",
    "person_name_provider": ".providers",
    "company_name_provider": ".providers",
    "cpf_provider": ".providers",
    "cnpj_provider": ".providers",
    "rg_provider": ".providers",
    "phone_provider": ".providers",
    "email_provider": ".providers",
    "address_provider": ".providers",
    "cep_provider": ".providers",
    "date_provider": ".providers",
    "datetime_provider": ".providers",
    "number_provider": ".providers",
    "decimal_provider": ".providers",
    "money_provider": ".providers",
    "choice_provider": ".providers",
    "boolean_provider": ".providers",
    "uuid_provider": ".providers",
    "sequence_provider": ".providers",
    "text_provider": ".providers",
    "code_provider": ".providers",
    "ConstraintValidator": ".constraints",
    "ConstraintRule": ".constraints",
    "DatasetBuilder": ".dataset_builder",
    "Dataset": ".dataset_builder",
    "DatasetRecord": ".dataset_builder",
    "TemplateEngine": ".template_engine",
    "SyntheticInferencer": ".inferencer",
    "ScreenRegistry": ".screen_registry",
    "JourneyDefinition": ".journey",
    "JourneyStep": ".journey",
    "JourneyDataset": ".journey",
    "JourneyInferencer": ".journey_inferencer",
    "JourneyBuilder": ".journey_builder",
    "ErrorDetector": ".error_detector",
    "DetectedError": ".error_detector",
    "JourneyVerifier": ".journey_verifier",
    "JourneyVerificationResult": ".journey_verifier",
    "CaptureParametrizer": ".capture_parametrizer",
    "CaptureTemplate": ".capture_parametrizer",
    "ParametrizedSession": ".capture_parametrizer",
    "SyntheticStressRunner": ".stress_runner",
    "SyntheticStressConfig": ".stress_runner",
    "StressRunResult": ".stress_runner",
    "ExpandedInferencer": ".expanded_inferencer",
    "ConditionalFlow": ".expanded_inferencer",
    "DataDependency": ".expanded_inferencer",
    "TransactionBlock": ".expanded_inferencer",
    "ReplayAdapter": ".replay_adapter",
    "ReplayAdapterConfig": ".replay_adapter",
    "HomologationReport": ".homologation_report",
    "MacroJourneyRunner": ".macro_journey",
    "MacroJourneyDefinition": ".macro_journey",
    "MacroJourneyStep": ".macro_journey",
    "MacroJourneyResult": ".macro_journey",
    "ScreenDiffer": ".screen_differ",
    "ScreenDiff": ".screen_differ",
    "ScreenDiffLine": ".screen_differ",
    "RemoteExecutor": ".remote_executor",
    "RemoteSessionResult": ".remote_executor",
    "RemoteExecutionResult": ".remote_executor",
    "Scheduler": ".scheduler",
    "ScheduleConfig": ".scheduler",
    "RegressionComparison": ".scheduler",
    "SessionRecorder": ".session_recorder",
    "RecordedSession": ".session_recorder",
    "ScreenExplorer": ".screen_explorer",
    "DiscoveredScreen": ".screen_explorer",
    "ExplorationResult": ".screen_explorer",
    "JUnitExporter": ".junit_exporter",
    "SnapshotBaseline": ".snapshot_baseline",
    "ScreenSnapshot": ".snapshot_baseline",
    "BaselineComparison": ".snapshot_baseline",
    "CSVExporter": ".csv_exporter",
    "QuickstartDiffer": ".csv_exporter",
    "QuickstartDiff": ".csv_exporter",
    "WatchMode": ".csv_exporter",
    "MetricsCollector": ".csv_exporter",
    "CRUDJourneyGenerator": ".crud_journey_generator",
    "CRUDJourneyConfig": ".crud_journey_generator",
    "DDLParser": ".ddl_parser",
    "DDLParseResult": ".ddl_parser",
    "JourneyValidator": ".journey_validator",
    "JourneyValidation": ".journey_validator",
    "SmartProviderRouter": ".smart_provider_router",
    "RelationshipResolver": ".relationship_resolver",
    "ResolvedForeignKey": ".relationship_resolver",
    "ResolvedLookup": ".relationship_resolver",
    "IntegratedPipeline": ".integrated_pipeline",
    "PipelineResult": ".integrated_pipeline",
    "DataSynthesizer": ".data_synthesizer",
    "InferredDataPlan": ".data_synthesizer",
    "RecordValidationResult": ".data_synthesizer",
    "PreflightValidationResult": ".data_synthesizer",
    "BulkGenerationResult": ".data_synthesizer",
    "InferredRoute": ".roteiro_model",
    "InferredRoutePhase": ".roteiro_model",
    "InferredRouteStep": ".roteiro_model",
    "ProgramEvidence": ".roteiro_model",
    "MenuEvidence": ".roteiro_model",
    "ReferenceRouteSummary": ".roteiro_model",
    "RoteiroSynthesizer": ".roteiro_synthesizer",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if not module_name:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
